export const bosForm = {
  stokKodu: "",
  ad: "",
  marka: "",
  ureticiKodu: "",
  barkod: "",
  anaKategoriId: "",
  altKategoriId: "",
  kategoriOzelDegerler: {},
  birim: "Adet",
  kdvOrani: 20,
  alisFiyati: "",
  satisFiyati: "",
  minimumSatisFiyati: "",
  stok: "",
  kritikSeviye: "",
  hedefStok: "",
  guvenlikStogu: "",
  siparisteAdet: "",
  rafAdresi: "",
  tedarikci: "",
  aciklama: "",
  fotograf: "",
  aktif: true,
  urunTipi: "Basit",
  setBilesenleri: [],
  paketBirimleri: [],
  satisBirimSekli: "sadeceTemel",
  fiyatDegisimNedeni: "",
};

